apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-application-ingress
  namespace: helm-application
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: helm-application-svc
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: helm-application-svc
                port:
                  number: 80
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
