apiVersion: v1
kind: Service
metadata:
  name: helm-application-svc
  namespace: helm-application
spec:
  type: {{ .Values.service.type }}
  selector:
    app: node
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  sessionAffinity: ClientIP
