replicaCount: 1

image:
  repository: akarizwei/node_test
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: sample-application-sa

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
  path: /
  host: ""
  tls:
    secretName: tls-secret

resources:
  limits:
    cpu: 0.5
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 50Mi

livenessProbe:
  initialDelaySeconds: 3
  periodSeconds: 3
  path: /
  port: 80
  httpHeader:
    name: X-Custom-Header
    value: Awesome
